services:
    zookeeper:
        image: zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            ALLOW_PLAINTEXT_LISTENER: 1
        depends_on:
            - zookeeper


    mongo:
        image: mongo
        ports:
            - "27017:27017"
    

    portal:
        build:
            context: ./portal
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - mongo
            - kafka
        environment:
            - NAME=portal-0
            - MONGO_URI=mongodb://mongo:27017/db

    consumer:
        build:
            context: ./consumer
            dockerfile: Dockerfile
        ports:
            - "3005:3005"
        depends_on:
            - portal
        environment:
            - NAME=consumer-0
            - MONGO_URI=mongodb://mongo:27017/db
            
    caddy:
        image: caddy:latest
        restart: unless-stopped
        ports:
            - "5011:5011"
        networks:
            - backend-net
        volumes:
            - ./frontend/Caddyfile:/etc/caddy/Caddyfile
            - ./frontend/app/dist:/srv

    data-populator:
        build:
            context: ./populate
            dockerfile: Dockerfile
        depends_on:
            - mongo
            - portal
            - consumer
