version: "3.8"

services:
    kafka-0:
        image: bitnami/kafka:3.4.1-debian-12-r21
        ports:
            - "9092:9092"
        environment:
            KAFKA_ENABLE_KRAFT: "yes"
            KAFKA_BROKER_ID: "0"
            KAFKA_CFG_NODE_ID: "0"
            KAFKA_CFG_PROCESS_ROLES: "controller,broker"
            KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0:9093"
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
        volumes:
            - kafka-data-0:/bitnami/kafka
        networks:
            - kafka-net

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - backend-net

    backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        depends_on:
            - mongo
            - kafka-0
        links:
            - mongo
        networks:
            - backend-net
            - kafka-net

volumes:
    kafka-data-0:

networks:
    backend-net:
    kafka-net:
