version: "3.8"

services:
    zookeeper:
        image: zookeeper
        ports:
            - "2181:2181"
        networks:
            - kafka-net

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper
        networks:
            - kafka-net

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - backend-net

    # backend:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.dev
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - mongo
    #         - kafka
    #     links:
    #         - mongo
    #     networks:
    #         - backend-net
    #         - kafka-net

networks:
    backend-net:
    kafka-net:
